# Generated by Django 4.0.4 on 2023-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_player_shirt_name_team_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('G', 'Goal'), ('A', 'Assist'), ('Y', 'YellowCard'), ('R', 'RedCard'), ('S', 'Substitution'), ('OG', 'OwnGoal')], max_length=2)),
                ('clock', models.CharField(max_length=10)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='teams.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='teams.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stage', models.CharField(max_length=20)),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Away', to='teams.team')),
                ('events', models.ManyToManyField(to='matches.event')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home', to='teams.team')),
            ],
        ),
    ]
