# Generated by Django 4.0.4 on 2022-11-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='short',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
